class Chitietlichhen {
  final String trangthai,
      trangthaidk,
      kenhdk,
      doituong,
      ngaysinh,
      hoten,
      nghenghiep,
      gioitinh,
      dantoc,
      quoctich,
      tinhkhaisinh,
      sodienthoai,
      chungminhthu,
      tinhthanhpho,
      huyen,
      xa,
      sonha,
      yeucaukham,
      phongkham,
      bacsi,
      thoigiankham,
      noidungkham,
      ghichu;
  Chitietlichhen({
    required this.trangthai,
    required this.trangthaidk,
    required this.kenhdk,
    required this.doituong,
    required this.hoten,
    required this.ngaysinh,
    required this.nghenghiep,
    required this.gioitinh,
    required this.dantoc,
    required this.quoctich,
    required this.tinhkhaisinh,
    required this.sodienthoai,
    required this.chungminhthu,
    required this.tinhthanhpho,
    required this.huyen,
    required this.xa,
    required this.sonha,
    required this.yeucaukham,
    required this.phongkham,
    required this.bacsi,
    required this.thoigiankham,
    required this.noidungkham,
    required this.ghichu,
  });
}

List<Chitietlichhen> Thongtin = [
  Chitietlichhen(
      trangthai: 'Đặt lịch thành công',
      trangthaidk: 'Đã đến khám',
      kenhdk: 'Qua VNCARE',
      doituong: 'Viện phí',
      hoten: 'dương thị mai anh',
      ngaysinh: '09/07/2009 ',
      nghenghiep: 'tri thức',
      gioitinh: 'nữ',
      dantoc: 'Kinh',
      quoctich: 'Việt Nam',
      tinhkhaisinh: 'Hà Nội',
      sodienthoai: '09999999999',
      chungminhthu: '03319823149189',
      tinhthanhpho: 'Hà Nội',
      huyen: 'Đống đa',
      xa: 'Nam từ liêm',
      sonha: '1102',
      yeucaukham: 'Khám sản',
      phongkham: 'Phòng khám số 1',
      bacsi: 'Nguyễn thu trang',
      thoigiankham: '09/08/2021',
      noidungkham: 'Khám sản',
      ghichu: 'Đã gọi xác nhận'),
];
